services:
  nifi2:
    image: apache/nifi:2.2.0
    volumes:
      - ./.nifi/v2/conf:/opt/nifi/nifi-current/conf
    ports:
      - "8080:8080"
      - "6000:6000"
      - "6001:6001"
    env_file:
      - .local-nifi.env
    networks:
      - default

  nifi1:
    image: apache/nifi:1.28.0
    volumes:
      - ./.nifi/v1/conf:/opt/nifi/nifi-current/conf
    ports:
      - "8080:8080"
      - "6000:6000"
      - "6001:6001"
    env_file:
      - .local-nifi.env
    restart: unless-stopped
    networks:
      - default

networks:
  default:
    driver: bridge
    external: false
