services:
  nifi2:
    image: apache/nifi:2.2.0
    volumes:
      - ./.nifi/v2/conf:/opt/nifi/nifi-current/conf
    ports:
      - "8080:8080"
      - "6000:6000"
      - "6001:6001"
    environment:
      - NIFI_WEB_HTTPS_PORT=8080
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=12345678Matanel!
    networks:
      - default

  nifi1:
    image: apache/nifi:1.28.0
    volumes:
      - ./.nifi/v1/conf:/opt/nifi/nifi-current/conf
    ports:
      - "8080:8080"
      - "6000:6000"
      - "6001:6001"
    environment:
      - NIFI_WEB_HTTPS_PORT=8080
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=12345678Matanel!
    restart: unless-stopped
    networks:
      - default

networks:
  default:
    driver: bridge
    external: false
